version: '3.8'

services:
    mychampionship-backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        image: mychampionship-backend
        container_name: mychampionship-backend
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - ./backend:/var/www/html/backend
        networks:
            - mychampionship-network

    mychampionship-frontend:
        build:
            context: .
            dockerfile: frontend/deploy.Dockerfile
        image: mychampionship-frontend
        container_name: mychampionship-frontend
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./frontend:/var/www/html/frontend
        networks:
            - mychampionship-network

    mychampionship-database:
        image: mysql:8.0
        container_name: mychampionship-database
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: mychampionship
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: 123456
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - mychampionship-network
        command: --default-authentication-plugin=mysql_native_password

networks:
    mychampionship-network:
        driver: bridge
